# Generated by Django 6.0 on 2025-12-30 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('smiles', models.TextField()),
                ('molecular_formula', models.CharField(blank=True, max_length=255)),
                ('molecular_weight', models.FloatField(blank=True, null=True)),
                ('structure_file', models.FileField(blank=True, null=True, upload_to='structures/')),
                ('image_2d', models.ImageField(blank=True, null=True, upload_to='molecule_images/')),
                ('is_active', models.BooleanField(default=False)),
                ('gene_target', models.CharField(blank=True, max_length=100)),
                ('toxicity_score', models.FloatField(blank=True, null=True)),
                ('solubility', models.FloatField(blank=True, null=True)),
                ('radioactivity', models.CharField(blank=True, max_length=50, null=True)),
                ('bioavailability', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Molecule',
                'verbose_name_plural': 'Molecules',
                'db_table': 'molecules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoleculeProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('property_value', models.TextField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('predicted', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='molecules.molecule')),
            ],
            options={
                'verbose_name': 'Molecule Property',
                'verbose_name_plural': 'Molecule Properties',
                'db_table': 'molecule_properties',
                'unique_together': {('molecule', 'property_name')},
            },
        ),
    ]
