# Generated by Django 6.0 on 2026-01-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=255)),
                ('total_entries', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Import Statistic',
                'verbose_name_plural': 'Import Statistics',
                'db_table': 'import_statistics',
                'ordering': ['-import_date'],
            },
        ),
    ]
