# Generated by Django 6.0 on 2025-12-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('toxicity', 'Toxicity'), ('solubility', 'Solubility'), ('activity', 'Activity'), ('bioavailability', 'Bioavailability')], max_length=50)),
                ('result', models.JSONField()),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prediction Request',
                'verbose_name_plural': 'Prediction Requests',
                'db_table': 'prediction_requests',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('search_type', models.CharField(choices=[('text', 'Text Search'), ('advanced', 'Advanced Search'), ('structure', 'Structure Search'), ('sequence', 'Sequence Search')], max_length=50)),
                ('results_count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'db_table': 'search_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('search', 'Search'), ('view_molecule', 'View Molecule'), ('predict', 'Prediction'), ('download', 'Download'), ('page_view', 'Page View'), ('login', 'Login'), ('logout', 'Logout')], max_length=50)),
                ('search_query', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'db_table': 'user_activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
