# Generated by Django 6.0 on 2025-12-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_userpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('recomended', 'Recomended'), ('dark', 'Dark')], default='light', max_length=15),
        ),
    ]
