# Generated by Django 6.0 on 2025-12-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_alter_userpreferences_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='page_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
