# Generated by Django 6.0 on 2025-12-30 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('molecules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoleculeViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.IntegerField(default=1)),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='molecules.molecule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molecule_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Molecule View History',
                'verbose_name_plural': 'Molecule View Histories',
                'db_table': 'molecule_view_history',
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'molecule')},
            },
        ),
    ]
