# Generated by Django 6.0 on 2025-12-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_moleculeviewhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='profile_photos/'),
        ),
    ]
